### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by Valleriite** [TehcJS/Chlorine#1]
Hi,
thanks for the mod but,
is it ready?
what does it do?
have a nice day

**Comment by Valleriite** [comment]
is this the same as this mod:https://www.curseforge.com/minecraft/mc-mods/chlorine
if so then this is just a forge port of sodium,
maybe they are not related, maybe this should be clarified.

**Comment by TehcJS** [comment]
When I initially created this, nothing else was called Chlorine. I guess I'll just delete this repository since it's incomplete and is confusing people. This was supposed to be an optimization mod for fabric, but school and ModFest got in the way. :/ Sorry!

**Comment by Valleriite** [comment]
hank you
